### ISSUE TITLE
Wrong Binder links on Gallery page

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/cookbook-gallery#102]
The gallery page at https://cookbooks.projectpythia.org gives (broken) links to https://mybinder.org

The Binder links on the Gallery should always match the Binder links on the README page for each cookbook. E.g. for the [HRRR Cookbook](https://projectpythia.org/HRRR-AWS-cookbook/README.html) the link should be 
http://binder.mypythia.org/v2/gh/ProjectPythia/HRRR-AWS-cookbook.git/main

I suggest this is a high priority to get fixed before AGU if possible.

**Comment by brian-rose** [comment]
@jukent it looks like the paths to mybinder.org are hard-coded here:
https://github.com/ProjectPythia/cookbook-gallery/blob/e4b3c79d1f8baa9817bb5598b5640fd0ddaabddc/site/_extensions/gallery_generator.py#L13

Do you have any ideas about how to pull the links directly from each README file instead?

**Comment by jukent** [comment]
Hmm I'll focus on this today.
It would be very easy to grab links from the config file, it is probably possible from the README as well.

**Comment by brian-rose** [comment]
Ok, I suggest priorizing the value from the _config.yaml file, because this is the one that the rendered JupyterBook uses.

I would like to develop some automation to place the same link in the README so there's only a single link that needs updating.

**Comment by jukent** [comment]
So all of the other cookbooks follow the same template, the HRR Cookbook is the only one whose repo is called "HRR Cookbook" but whose Binder link is different.

Could we enforce this template? The fastest change would be to change the name of that repository to match the formula.

**Comment by brian-rose** [comment]
With #103 we fixed the links. There is a display issue for the link badges affecting the Chrome browser. Will open a separate issue about that.
