### ISSUE TITLE
Binder badges on Gallery page don't display on Chrome browser

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/cookbook-gallery#104]
As discussed in #103, the new Binder badges with the correct links drawn dynamically from each Cookbook's `_config` file do not display properly in the Chrome browser.

**Comment by brian-rose** [comment]
Here's a partial screenshot of https://cookbooks.projectpythia.org on Safari on MacOS 12.6.1:
<img width="1624" alt="Screen Shot 2022-12-07 at 10 37 34 PM" src="https://user-images.githubusercontent.com/9097307/206350759-de4c08b0-1406-490c-8639-04b351d7dca8.png">

and a screenshot of the same page on Chrome:
<img width="1312" alt="Screen Shot 2022-12-07 at 10 39 05 PM" src="https://user-images.githubusercontent.com/9097307/206350882-e7633621-4227-440d-b0b1-64b8b9c8becd.png">

**Comment by brian-rose** [comment]
The badges are created dynamically at site build time using [this code](https://github.com/ProjectPythia/cookbook-gallery/blob/21d9234f2b094303c8fd3bed083335f18d9be2c1/site/_extensions/gallery_generator.py#L24)

Why does it fail on Chrome but not other browsers?  (Firefox is also confirmed to work as expected) @ProjectPythia/infrastructure

**Comment by brian-rose** [comment]
The rendered HTML for the HRRR-AWS cookbook Binder badge on the Gallery page [here](https://github.com/ProjectPythia/cookbook-gallery/blob/9f578336b4bb0b34b132e6d26f20f51c7fb8b7a9/index.html#L262) looks like this:
```
<a class="reference external" href="http://binder.mypythia.org/v2/gh/ProjectPythia/HRRR-AWS-cookbook.git/main"><img alt="Binder" src="http://binder.mypythia.org/badge_logo.svg"/></a>
```

while the [rendered HTML](https://github.com/ProjectPythia/HRRR-AWS-cookbook/blob/b8d10db08cfd574cba38f4dc2b10e0a0a167c522/README.html#L343) for the same badge on the [README page](https://projectpythia.org/HRRR-AWS-cookbook/README.html) (which looks fine on Chrome) is this:
```
<a class="reference external" href="http://binder.mypythia.org/v2/gh/ProjectPythia/HRRR-AWS-cookbook.git/main"><img alt="Binder" src="http://binder.mypythia.org/badge_logo.svg" /></a>
```

Other than a bit of whitespace, they look identical to me. No idea why the first one does not render properly on Chrome.

**Comment by ktyle** [comment]
Bringing up the Developer's Console in Chrome, it is 1) replacing http with https, and then 2)  throwing an invalid certificate authority error when it tries to load the svg using that protocol. It's happening on my version of Chrome both for the Gallery and README pages. 

More impetus for me to get a new Jetstream2 Binderhub instance up which uses https and has a recognized certificate authority.

**Comment by brian-rose** [comment]
This should go away when our new Pythia binder service is up and running!

**Comment by brian-rose** [comment]
Update: this problem is *mostly* resolved since most Cookbooks on the gallery are now linking to the new Pythia binder which uses https. 

There are still a couple of Cookbooks on the gallery that are not linking to the new Binder:
- Landsat ML Cookbook
- xbatcher for Machine Learning Cookbook

There are PRs open in both those repos to get them updated to the latest infrastructure.
