### ISSUE TITLE
Binder badge images do not render in the gallery on Chrome

### ISSUE THREAD

**Issue by tylere** [ProjectPythia/cookbook-gallery#125]
On https://cookbooks.projectpythia.org/ the Binder badges are not rendering correctly:

<img width="245" alt="image" src="https://user-images.githubusercontent.com/92862/224807930-19d8ae0e-b41e-4641-9161-e9e2cd3a9ac6.png">

The Chrome developer console error:
> Mixed Content: The page at 'https://cookbooks.projectpythia.org/' was loaded over HTTPS, but requested an insecure element 'http://binder.mypythia.org/badge_logo.svg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

**Comment by brian-rose** [comment]
Thanks for this report @tylere! This is a known issue with how Chrome treats http links. We are hoping to launch a new and improved Pythia binder shortly that will be served over https so this issue should go away.

**Comment by brian-rose** [comment]
Closing this as the same issue is described in #104
