### ISSUE TITLE
Use cookbook infrastructure

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/cookbook-gallery#131]
### Root Repository Name

ProjectPythia / cookbook-gallery

### Did you check if your contribution would be better suited as an addition to an existing Cookbook, before generating a new one?

yes

### Additional comments

To simplify future maintenance and reduce dependencies, it would be good to update our GitHub Actions infrastructure for building, previewing, and link-checking to use the same actions as Pythia Cookbooks.

**Comment by brian-rose** [comment]
For clarification, this isn't a new cookbook submission but an issue about the infrastructure we use to build and publish the gallery page!

**Comment by brian-rose** [comment]
This should subsume #108 since a link checker is included in the cookbook build infrastructure.
