### ISSUE TITLE
Adding a Tiles Sources Cookbook

### ISSUE THREAD

**Issue by ahuang11** [ProjectPythia/cookbook-gallery#143]
### Root Repository Name

web-map-feature-services-cookbook

### Additional comments

Foundations:
- What is WMTS?
- Static tiles
- Interactive tiles

Example Workflows:
- ESRI maps
- NOAA radar
- NASA satellite
- Crop climate
- Custom tiles
- Offline tiles
- Dashboard of tiles

References:
https://idpgis.ncep.noaa.gov/arcgis/rest/services/NWS_Observations/radar_base_reflectivity/MapServer
https://discourse.holoviz.org/t/using-geoviews-tile-sources-offline/4859/6
https://sedac.ciesin.columbia.edu/maps/services#crop-climate

**Comment by r-ford** [comment]
Reopening to test automation. The repo name was in the wrong format for #144 to work.
