### ISSUE TITLE
Update Gallery with NA-CORDEX visualization cookbook

### ISSUE THREAD

**Issue by bonnland** [ProjectPythia/cookbook-gallery#151]
### Root Repository Name

ProjectPythia/na-cordex-viz-cookbook

### Did you check if your contribution would be better suited as an addition to an existing Cookbook, before generating a new one?

yes

### Additional comments

Hi, 

Just wanted to add this recent cookbook to the gallery.

Let me know if I can provide anything.   Thanks!

**Comment by brian-rose** [comment]
@jukent did something go wrong with the automation here? I don't see a PR to add this to the gallery.

**Comment by jukent** [comment]
Yeah the actions show up but are all skipped. I haven't had a chance to solve this today.

**Comment by jukent** [comment]
The action only runs if the issue has the tag "cookbook-gallery-submission" - since this used to work I'm wondering if this tag was deleted in our effort to standardize tags across repos in the organization. I'll look at adding the tag back to the issue template. Hopefully this is why the job has been skipped.

**Comment by jukent** [comment]
Adding the label, closing, and reopening to see if this is the problem.

**Comment by jukent** [comment]
Proposing a fix in https://github.com/ProjectPythia/cookbook-gallery/pull/154

**Comment by jukent** [comment]
The action is still being skipped - https://github.com/ProjectPythia/cookbook-gallery/actions/runs/5385005821 

I can look at this more after the holiday.

**Comment by bonnland** [comment]
Hi, I see other cookbooks getting added to the cookbook Gallery.   Is this cookbook also ready to go?  It would be great to see it published.

**Comment by jukent** [comment]
Making a PR to fix this now. Sorry this slipped!

**Comment by jukent** [comment]
Notes from @r-ford 

> Looks good! @bonnland Just a couple comments:
 Ideally, the notebook should have the Overview, Prerequisites, Imports, Summary, and References sections from the template
Some more background info on NA-CORDEX would be helpful, either in the notebook or the README

**Comment by bonnland** [comment]
OK, I will take a look and add some words later this week when I have some free time.
Thanks for the quick turnaround!

**Comment by bonnland** [comment]
I've added documentation in 

https://github.com/ProjectPythia/na-cordex-viz-cookbook/pull/11
