### ISSUE TITLE
Public cloud storage needed to support cookbook data

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/cookbook-gallery#155]
For cookbooks that require data sets that are too large for GitHub, and are not available from freely accessible source, we need to provide an alternate storage location (e.g. Jetstream2).

**Comment by ktyle** [comment]
We have 10 TB on our existing allocation, so I will look into writing a pangeo-forge recipe that could place at least one test dataset there.

**Comment by brian-rose** [comment]
> We have **1 TB** (not 10 as I mentioned on the call, sorry) on our existing JS2 allocation, so I will look into writing a pangeo-forge recipe that could place at least one test dataset there.

It will be fantastic to have a working example!

This will let us develop a (hopefully simple) process by which existing or new Cookbooks can request and get access to some of this storage. Filling up the existing allocation will make it that much easier to build a coherent proposal for a larger storage allocation via ACCESS.
