### ISSUE TITLE
Cookbook Gallery issue/PR automation not working

### ISSUE THREAD

**Issue by r-ford** [ProjectPythia/cookbook-gallery#158]
The jobs in the [Update Cookbook Gallery workflow](https://github.com/ProjectPythia/cookbook-gallery/actions/workflows/update-cookbook-gallery.yaml) are being skipped. As a result, a PR to update the gallery will not be automatically opened when an issue is opened using the template (for example, #151).

**Comment by brian-rose** [comment]
@r-ford will investigate to see if this has been fixed.

**Comment by r-ford** [comment]
Fixed in #167
