### ISSUE TITLE
Cookbook duplicated in gallery

### ISSUE THREAD

**Issue by r-ford** [ProjectPythia/cookbook-gallery#201]
I'm seeing the Gridding cookbook twice in the gallery:

![image](https://github.com/ProjectPythia/cookbook-gallery/assets/50349951/63c73b44-46c3-4033-92a5-3d7fc175a554)

Based on [cookbook_gallery.txt](https://github.com/ProjectPythia/cookbook-gallery/blob/main/site/cookbook_gallery.txt), the second one should be the VAPOR cookbook.

**Comment by brian-rose** [comment]
Interesting.

I don't know if this is the cause, but the [_config.yml file for the Vapor cookbook](https://github.com/ProjectPythia/vapor-python-cookbook/blob/main/_config.yml) is not up to date with format expected in the [latest cookbook template](https://github.com/ProjectPythia/cookbook-template/blob/main/_config.yml)

**Comment by brian-rose** [comment]
Unfortunately https://github.com/ProjectPythia/vapor-python-cookbook/pull/15 did not resolve the issue. The VAPOR Cookbook still doesn't appear in the gallery.
