### ISSUE TITLE
cookbook gallery filters broken

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/cookbook-gallery#207]
The Cookbook Gallery filters do not seem to be operational. Navigate to the [gallery](https://cookbooks.projectpythia.org/). Click on either of the filters, `Domain` or `Package`. Nothing happens.

**Comment by brian-rose** [comment]
I think this is being worked on in https://github.com/ProjectPythia/cookbook-gallery/pull/199

**Comment by brian-rose** [comment]
Overall issue is being tracked at https://github.com/ProjectPythia/projectpythia.github.io/issues/419

**Comment by jukent** [comment]
New PR to fix this is in https://github.com/ProjectPythia/cookbook-gallery/pull/208

Functionality is back, but I was forced to use new Sphinx classes and so the styling isn't pretty.

**Comment by jukent** [comment]
Okay. It can be merged today as is if you approve, and I'll open a new issue for improving the styling. This same fix needs to be made in the resource gallery.

I'm OOO today so I can work on that on Monday. I'll document the changes better for anyone who wants to learn/in case something breaks again.

**Comment by brian-rose** [comment]
Sounds good. I'll merge #208 now and open a placeholder issue about the styling and documentation.
