### ISSUE TITLE
Update gallery with ocean biogeochemistry cookbook

### ISSUE THREAD

**Issue by rmshkv** [ProjectPythia/cookbook-gallery#211]
### Root Repository Name

ocean-bgc-cookbook

### Did you check if your contribution would be better suited as an addition to an existing Cookbook, before generating a new one?

yes

### Additional comments

I'm still [troubleshooting](https://discourse.pangeo.io/t/generating-zenodo-doi-for-pythia-cookbook/4308/3) the Zenodo DOI creation, but everything else should be set up, so I figured I'd go ahead and submit.

**Comment by ktyle** [comment]
@rmshkv it looks like the DOI has been minted successfully; can you please confirm and close if so?

**Comment by rmshkv** [comment]
@ktyle Yep, the DOI is all set now, but the issue is about submitting the cookbook to the cookbook gallery, which I don't believe has happened yet.

**Comment by rmshkv** [comment]
Hi, just bumping this issue! Are there any changes I need to make before the cookbook can be added to the gallery?

**Comment by clyne** [comment]
Sorry for the delay, @rmshkv . The team is working to move this forward.

**Comment by jukent** [comment]
Hi I made some minor adjustments to the Cookbook here: https://github.com/ProjectPythia/ocean-bgc-cookbook/pull/5 

Once those are merged I am confident adding this to the Cookbook gallery.
Thanks for all of your hard work and good luck on your next chapter.

**Comment by jukent** [comment]
Dealt with code reuse per @kmpaul 's [suggestion](https://discourse.pangeo.io/t/code-re-use-in-cookbooks/4405/3) in https://github.com/ProjectPythia/ocean-bgc-cookbook/pull/6
